export default {
  userTokens: 'awaken-user-tokens',
  activeListUrls: 'awaken-active-listUrls',
  awakenFavList: 'awaken-favList',
  userAssetHidden: 'awaken-user-asset-hidden-flag',
  userPriceImpact: 'awaken-user-price-impact',
  userSlippageTolerance: 'awaken-user-slippage-tolerance',
  userExpiration: 'awaken-user-expiration',
  userTokenSort: 'awaken-user-token-sort',
  userIsExpert: 'awaken-user-is-expert',
  cid: 'awaken-cid',
  userChainId: 'awaken-user-chain-id',
  contractsFileDescriptorBase64: 'contracts-file-descriptor-base64',
  awakenAssetSymbol: 'awaken-asset-symbol',
};
